apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-viney
  namespace: viney-namespace
spec:
  type: ClusterIP
  selector:
    app: nginx-pod-lbl
  ports:
    - name: nginx-app-port
      port: 80
      targetPort: 80
