apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-viney
  namespace: viney-namespace
  labels:
    app: nginx-pod-lbl
spec:
  containers:
    - name: nginx-cont
      image: nginx:1.22.1
      ports:
        - containerPort: 80
  restartPolicy: Never
